config/routes.rb
Clubtrack::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :users, :clubs, :members
  resources :events do
    member do
      get :user_lookup, :attendance
      post :submit_attendance
    end
  end


  root :to => 'welcome#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/club.rb
class Club < ActiveRecord::Base
  has_paper_trail
  belongs_to :user
  has_many :members, dependent: :destroy
  has_many :events, dependent: :destroy

  attr_accessor :add_officer_email, :add_officer_role

  validates_presence_of :user, :name
  
  attr_accessible :name, :description, :add_officer_email, :clubs_users_attributes

  has_many :clubs_users, dependent: :delete_all

  accepts_nested_attributes_for :clubs_users, allow_destroy: true

  before_validation :add_new_officer


  def add_new_officer
    return if add_officer_email.blank?
    user = User.where(email: add_officer_email).first
    if user.blank?
      errors.add :add_officer_email, 'was not found. Make sure this user has signed in to the website.'
      return
    end

    if clubs_users.where(user_id: user.id).any?
      errors.add :add_officer_email, 'already exists  '
      return
    end

    clubs_users << ClubsUser.new do |u|
      u.user = user
      u.club = self
      u.role = 'admin' # TODO: don't hard code!
    end

  end
  
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController


  before_filter :default_breadcrumbs
  
  def index
    @grid = initialize_grid @clubs.includes(:user)
  end
  
  def new; end
  
  def create
    @club.user = current_user
    if @club.save
      flash[:success] = "Club has been created"
      return redirect_to clubs_path
    end
    render :action => 'new'
  end
  
  def show
    session[:club_id] = @club.id
  end

  def edit
    add_breadcrumb @club.name, @club
  end

  def update
    if @club.update_attributes params[:club]
      flash[:success] = 'Club updated successfully!'
      return redirect_to edit_club_path(@club)
    end
    render action: :edit
  end


  def destroy
    if @club.destroy
      session.delete :club_id
      flash[:success] = 'Club has been purged from database!'
      redirect_to :root
    else
      flash[:error] = 'Unable to delete club!'
      render action: :show
    end
  end
end

app/views/clubs/_form.html.erb
<%= form.item(:name){ form.text_field :name } %>
<%= form.item(:description){ form.text_area :description } %>

app/views/clubs/edit.html.haml
= page_title 'Edit Club', @club.name
= pretty_form_for @club do |f|
  = render partial: 'form', object: f

  %h3 Other Admins
  %p These people have access to the club. Check the box to remove them.

  %ul{style: 'list-style: none'}
  = f.fields_for :clubs_users do |u|
    %li{ style: 'list-style:none;vertical-align:middle;margin-left:15px'}
      %label.checkbox
        = u.check_box :_destroy
        = u.object.user.full_name
        = " / #{u.object.role}"


  %p Add a person by entering their <b>email address</b>:

  .control-group
    = f.label :add_officer_email, class: 'control-label'
    .controls
      = f.text_field :add_officer_email

  .form-actions
    = link_to 'Cancel', @club, class: 'btn'
    = f.submit 'Submit', class: 'btn btn-primary'

app/views/clubs/index.html.haml
= page_title 'My Clubs'

- if current_user.max_clubs_reached?
  .alert.alert-info
    You have reached the maximum number of clubs you can create.



- if @clubs.any?
  = grid @grid do |g|
    - g.column name: 'Name', attribute: 'name' do |club|
      - link_to club.name, club
    - g.column name: 'Description', attribute: 'description' do |club|
      - truncate club.description
    - g.column name: 'Owner', attribute: 'last_name', model: User do |club|
      - club.user.full_name
    - g.column name: 'Club Since', attribute: 'created_at' do |club|
      - club.created_at.to_date



- else
  %p
    %b You don't have any clubs!
    Click the link below to make a club.

.form-actions
  - if can? :create, Club
    = link_to 'Create Club', new_club_path, class: 'btn btn-primary'

app/views/clubs/new.html.erb
<%= page_title 'Create Club' %>
<div class="alert alert-info">
  You can create a maximum of <%= User::MAX_CLUB_COUNT %> clubs.
</div>
<%= pretty_form_for(@club) do |f| %>
  <%= render :partial => 'form', :object => f %>
  <%= f.submit_area do %>
    <%= link_to 'Cancel', clubs_path, :class => 'btn' %>  
  <% end %>
<% end %>

app/views/clubs/register_user.html.erb
<div class="hero-unit" id="register-area">
  <%= page_title "Register for #{@club.name}" %>
  <p>Please enter your ASURITE id below</p>
  <form method="get" id="asuritefun" data-url="<%= url_for :action => 'user_lookup', :format => :json %>">
    <input id="asurite" type="text">
    <span id="email-text">
      @asu.edu
    </span>
  </form>
  <p id="help-text">
    Press <b>ENTER</b> to continue
  </p>
</div>

app/views/clubs/show.html.erb
<%= page_title @club.name %>
<p><%= @club.description %></p>
<div class="row">
  <div class="span6">
    <h2>Upcoming Events <small><%= @club.events.upcoming.count %> total</small></h2>
    <ul>
    <% @club.events.upcoming.order("meeting_start ASC").each do |event| %>
      <li><%= link_to event.name, event %> <%= event.meeting_start.strftime("%b %d") %></li> 
    <% end %>
    </ul>
    <p>
      <%= link_to 'All Events', events_path %>
    </p>
  </div>
  <div class="span6">
    <h2>Top 10 Members</h2>
    <p>Displayed members are only for this semester.</p>
    <ul>
    <% @club.members.current_semester.with_statistics(@club.events.count).top.limit(10).each do |m| %>
      <li><%= m.full_name %> <em><%= m.attendance_count %> - <%= number_to_percentage (m.attendance_percent * 100), :precision => 2 %></em>
    <% end %>
    </ul>
    <%= link_to 'All Members', members_path %>
  </div>
</div>

<div class="form-actions">
  <%# link_to 'Edit', edit_club_path(@club), :class => 'btn btn-primary' %>
  <%= link_to 'New Event', new_event_path, :class => 'btn' %>

  <% if can? :edit, @club %>
    <%= link_to 'Edit Club', edit_club_path(@club), class: 'btn btn-primary' %>
  <% end %>
  <% if can? :delete, @club %>
  <%= link_to 'Delete Club', @club, class: 'btn btn-danger', style: 'float:right', method: 'delete',
        confirm: 'Are you sure you want to delete this club? This cannot be undone!' %>



  <% end %>
</div>