config/routes.rb
Clubtrack::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :users, :clubs, :members
  resources :events do
    member do
      get :user_lookup, :attendance
      post :submit_attendance
    end
  end


  root :to => 'welcome#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_paper_trail
  belongs_to :club
  has_and_belongs_to_many :members, :join_table => 'attendances'
  has_many :attendances, dependent: :destroy
  scope :upcoming, ->{ where('DATE(meeting_stop) >= ?', Date.today) }
  
  validates_presence_of :club, :name, :meeting_start, :meeting_stop
  attr_accessible :name, :description, :meeting_start, :meeting_stop
  
  def new_members
    Member.joins(:attendances).where("attendances.event_id = ? AND attendances.first_event = ?", id, true)
  end
  
  def existing_members
    Member.joins(:attendances).where("attendances.event_id = ? AND attendances.first_event = ?", id, false)
  end
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  
  require 'nokogiri'
  require 'net/https'
  
  before_filter :ensure_club_selected, :default_breadcrumbs, :add_curr_club_crumb
  
  
  
  def index
    @events = Event.select('events.*, COUNT(event_id) AS attendance_count').
        where(:club_id => @curr_club.id).joins('LEFT JOIN `attendances` ON `attendances`.`event_id` = `events`.`id`').
        group('event_id')
    @grid = initialize_grid @events, order: 'events.meeting_start', order_direction: 'ASC',
        custom_order: { 'attendances.id' => 'attendance_count'}
  end
  
  def new
    add_breadcrumb "Events", events_path
  end
  def show
    add_breadcrumb "Events", events_path
    if ex = params[:export]
      s = @event.new_members      if ex == 'new'
      s = @event.existing_members if ex == 'existing'
      s = @event.members          if ex == 'all'
      return export_members(s) if s
    end
  end
  def edit
     add_breadcrumb "Events", events_path
     add_breadcrumb @event.name, url_for(@event)
  end
  def update
    if @event.update_attributes(params[:event])
      flash[:success] = "Event Updated!"
    end
    render :action => :edit
  end
  def create
    @event.club = @curr_club
    if @event.save
      flash[:success] = "Event has been created"
      return redirect_to @event
    end
    render :action => :new
  end
  

  
  
  def attendance
    @club = @event.club
    @member = Member.new do |m|
      m.club = @club
    end
    render :layout => 'attendance'
  end
  
  def submit_attendance
    @club = @event.club
    @member = @club.members.new(params[:member])
    first_event = true
    
    # User already exists
    if @club.members.where(:email => @member.email).any?
      @member = @club.members.where(:email => @member.email).first
      # Current logic implies a new member has not signed in
      first_event = false
    else
      unless @member.save
        return render :action => :attendance, :layout => 'attendance'
      end
    end
    
    # Already attended
    if @event.attendances.where(:member_id => @member.id).any?
      flash[:success] = "You've already signed in, #{@member.first_name}!"
    else
      attendance = @event.attendances.new do |a|
        a.member_id    = @member.id
        a.signed_in_at = DateTime.now
        a.first_event  = first_event
      end
      attendance.save!
      flash[:success] = "Thanks for signing in, #{@member.first_name}!"
    end
    
    
    
    return redirect_to :action => 'attendance', :id => @event.id
  end
  
  
  def user_lookup
    data = nil
    success = false

    # Lookup existing email - save time!
    lookup = current_club.members.where('asurite = :p OR email = :p', p: params[:asurite]).first
    unless lookup.nil?
      success = true
      data    = {
          first_name: lookup.first_name,
          last_name:  lookup.last_name,
          email:      lookup.email,
          asurite:    lookup.asurite
      }
    end

    begin
      if data.nil?
        url = URI.parse("https://webapp4.asu.edu/directory/ws/search?asuriteId=" + CGI::escape(params[:asurite]))
        http = Net::HTTP.new(url.host, url.port)
        http.use_ssl = true
        result = http.get(url.path + "?" + url.query)
        xml = Nokogiri::XML(result.body)

        data = {
          :first_name => xml.xpath("//firstName[1]").text,
          :last_name  => xml.xpath("//lastName[1]").text,
          :email      => xml.xpath("//email[1]").text,
          :asurite    => xml.xpath("//asuriteId[1]").text
        }

        success = !data[:email].blank?
      end

    rescue Exception
      respond_to do |format|
        format.json { render :json => {:success => false}}
      end
    end

    respond_to do |format|
      format.json { render :json => {:success => success, :data => data}}
    end
  end
  
end

app/views/events/_form.html.erb
<%= form.item(:name) { form.text_field :name } %>
<%= form.item(:description) { form.text_area :description } %>

<%= form.item(:meeting_start) { form.datetime_range :meeting_start, :meeting_stop } %>

app/views/events/attendance.html.erb
<% global_css_js_file("attendance") %>

<% if @member.errors.any? %>
<div id="error_explanation">
  <h2>There were some errors signing you in!</h2>
  <ul><% @member.errors.full_messages.each do |m| %><li><%= m %></li><% end %></ul>
</div>
<% end %>
<div class="hero-unit" id="register-area">
  <div class="pre-header">
    <%= @event.name %>
  </div>
  <%= page_title @event.club.name %>
  
  <!-- Auto ASURITE information -->
  <div id="asurite-completion">
    <p>Please enter your <b>my.asu.edu username</b> or another email address below to sign in to this event.</p>
    <form method="get" id="asuritefun" data-url="<%= url_for :action => 'user_lookup', :format => :json %>" autocomplete="off">
      <input id="asurite" type="text" placeholder="jsmith1">
      <!-- <span id="email-text">
        @asu.edu
      </span> -->
    </form>
  </div>
  
  <!-- Manual Entry -->
  <div id="user-information">
    <p>
      Please enter the following user information to continue
    </p>
    <%= form_for(@member, :url => {:action => 'submit_attendance', :id => @event.id }, :html => {:class => "form-inline", :autocomplete => 'off'}) do |f| %>
      <div class="label-magic">
        <%= f.label :first_name %>
        <%= f.label :last_name %>
        <%= f.label :email %>
      </div>

      <div class="fields-magic">

        <%= f.text_field :first_name, :placeholder => 'Sparky' %>
        <%= f.text_field :last_name, :placeholder => 'Sundevil' %>
        <%= f.text_field :email, :placeholder => 'sparky@asu.edu' %>
      </div>

      <%= f.hidden_field :asurite %>

      <p style="margin-top:10px">
        <%= f.submit "Submit", :class => 'btn btn-primary' %>
        <a href="#" class="manual-lookup" style="font-size: 12px;margin-left: 5px">Automatic Lookup</a>
      </p>
    <% end %>
  </div>

  <div class="help-text" id="help-text">
    Press ENTER to continue &sdot; <a href="#" class="manual-lookup">Manual Entry</a>
   </div>
</div>
<p style="font-size:11px">
  <%= link_to("Return to Event", @event) %>
</p>

app/views/events/edit.html.erb
<%= page_title "Edit Event", @event.club.name %>
<%= pretty_form_for(@event) do |f| %>
  <%= render :partial => 'form', :object => f %>
  <%= f.submit_area do %>
    <%= link_to 'Cancel', @event, :class => 'btn' %>  
  <% end %>
<% end %>

app/views/events/index.html.haml
= page_title "Events", @curr_club.name

- if @events.any?
  = grid @grid do |g|
    - g.column name: 'Name', attribute: 'name'
    - g.column name: 'Start Time', attribute: 'meeting_start'
    - g.column name: 'Stop Time', attribute: 'meeting_stop'
    - g.column name: 'Attendance', attribute: 'id', model: Attendance, filter: false do |event|
      - event.attendance_count
    - g.column do |event|
      - link_to 'View', event, class: 'btn btn-small'

- else
  %p
    %b You don't have any events!
    Click the link below to make an event.



.form-actions
  = link_to 'New Event', new_event_path, class: 'btn btn-primary'
  = link_to 'Cancel', @curr_club, class: 'btn'

app/views/events/new.html.erb
<%= page_title "New Event", @curr_club.name %>
<%= pretty_form_for(@event) do |f| %>
  <%= render :partial => 'form', :object => f %>
  <%= f.submit_area do %>
    <%= link_to 'Cancel', clubs_path, :class => 'btn' %>  
  <% end %>
<% end %>

app/views/events/show.html.erb
<%= page_title @event.name, @event.club.name %>
<p>
  <%= @event.description %>
</p>
<div class="row">
  <div class="span6">
    <h2>Existing Members <small><%= @event.existing_members.count %> total</small></h2>
    <% if @event.existing_members.any? %>
      <p>These people have signed up for other meetings</p>
      <ul>
      <% @event.existing_members.each do |m| %>
      <li><%= m.full_name %> (<a href="mailto:<%= m.email %>"><%= m.email %></a>)</li>
      <% end %>
      </ul>
    <% else %>
      <p>
        No existing members have signed up to this meeting.
      </p>
    <% end %>
  </div>
  
  <div class="span6">
    <h2>New Members <small><%= @event.new_members.count %> total</small></h2>
    <% if @event.new_members.any? %>
      <p>This was the first event for these members</p>
      <ul>
        <% @event.new_members.each do |m| %>
        <li><%= m.full_name %> (<a href="mailto:<%= m.email %>"><%= m.email %></a>)</li>
      <% end %>
      </ul>
    <% else %>
      <p>No new members have signed up for this meeting!</p>
    <% end %>
  </div>
  
</div>

<p>
  Export data:
    <%= link_to 'new members', export: 'new' %> &sdot;
  <%= link_to 'existing members', export: 'existing' %> &sdot;
  <%= link_to 'all members', export: 'all' %>
</p>

<div class="form-actions">
  <%= link_to 'Edit Event', edit_event_path(@event), :class => 'btn btn-primary' %>
  <%= link_to 'Take Attendance', {:action => 'attendance', :id => @event.id} , :class => 'btn' %>
  <%= link_to 'Cancel', events_path, :class => 'btn' %>
</div>